#!/usr/bin/env php
<?php

use App\Hook\Certbot;

require __DIR__.'/vendor/autoload.php';

list($command, $domain) = array_slice($argv, 1);

$certbot = new Certbot();

if ($command === 'create') {
	$certbot->createTXTRecordForDomain($domain, '4376834');
} elseif ($command === 'delete') {
	$certbot->deleteTXTRecordForDomain($domain);
}
